
set(ENABLED_GEMS
    Atom_AtomBridge
    Camera
    CameraFramework
    EMotionFX
    FastNoise
    SurfaceData
    GradientSignal
    Vegetation
    GraphModel
    LandscapeCanvas
    ImGui
    LmbrCentral
    LyShine
    Maestro
    NvCloth
    SceneProcessing
    TextureAtlas
    WhiteBox
    DebugDraw
    EditorPythonBindings
    QtForPython
    DccScriptingInterface
    PythonAssetBuilder
    StartingPointMovement
    StartingPointCamera
    PhysX
    PhysXDebug
    Terrain
    PrimitiveAssets
    ScriptCanvas
    ScriptCanvasPhysics
    ScriptCanvasTesting
    ScriptedEntityTweener
    StartingPointInput
    GameState
    ScriptEvents
    ScriptCanvasDeveloper
    HttpRequestor
    CrashReporting
    ArchVis
    UiBasics
    ReferenceMaterials
    Sponza
    DevTextures
    MaterialEditor
    ScriptAutomation
    DiffuseProbeGrid
)
